### ISSUE TITLE
code doesn't have a license file

### ISSUE THREAD

**Issue by dmose** [nicjansma/talks#1]
This is very interesting and helpful stuff; thanks for writing it!

Some of this code (particularly the examples) would particularly helpful to reuse, but the code doesn't seem to have a file indicating what license it is under...

**Comment by nicjansma** [comment]
Hi @dmose!  Everything in this repository is covered under the MIT license:

https://github.com/nicjansma/talks/blob/master/LICENSE

Enjoy!

**Comment by dmose** [comment]
So it is; sorry I missed that -- thanks!
